//! `OperatorConfirmation` value object and `SignedConfigFlag` placeholder.

use serde::{Deserialize, Serialize};

/// A placeholder JWT-based signed config flag for non-Claude-Code clients.
///
/// Per ADR-0011 Amendment: MCP clients that cannot issue slash commands may
/// authenticate reveals via an Ed25519-signed JWT attesting that the client's
/// operator trusts its turn-boundary enforcement.  Actual JWT verification is
/// deferred to the adapter layer; the domain only holds the raw strings.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SignedConfigFlag {
    /// The raw Ed25519-signed JWT (base64url-encoded dot-separated claims).
    pub jwt: String,
    /// The key identifier used to look up the verification public key.
    pub key_id: String,
}

/// The two-flag Operator Confirmation model (ADR-0011).
///
/// Authorization rules:
///
/// | Condition                | Required flags |
/// |--------------------------|----------------|
/// | All sensitivities        | `slash_command == true` |
/// | `sensitivity == high`    | `slash_command == true` AND `oob_ack == true` |
/// | `sensitivity < high`     | `slash_command == true` is sufficient |
///
/// The `slash_command` flag is set by the Claude Code client process, not
/// generated by the LLM through tool-call arguments.  The `oob_ack` flag is
/// set by the OOB Notifier after the operator physically acknowledges a
/// confirmation request on a channel outside the MCP transport.
///
/// ```
/// use merkle_domain_access_mediation::operator_confirmation::OperatorConfirmation;
///
/// let confirm = OperatorConfirmation {
///     slash_command: true,
///     oob_ack: false,
///     signed_config_flag: None,
/// };
/// assert!(confirm.slash_command);
/// assert!(!confirm.oob_ack);
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OperatorConfirmation {
    /// `true` when the Claude Code client verified a `/merkle-reveal` slash
    /// command was issued by the human operator.
    pub slash_command: bool,
    /// `true` when an OOB Confirmation was acknowledged outside the MCP
    /// transport channel.
    pub oob_ack: bool,
    /// Optional JWT-based attestation for non-Claude-Code clients.
    /// A valid `signed_config_flag` is treated as equivalent to
    /// `slash_command = true` by the adapter layer after signature verification.
    /// It does NOT satisfy the OOB requirement for `sensitivity = high`.
    pub signed_config_flag: Option<SignedConfigFlag>,
}

impl OperatorConfirmation {
    /// Returns `true` if the slash-command confirmation is satisfied.
    ///
    /// Satisfied when `slash_command == true` OR a `signed_config_flag` is
    /// present (adapter verifies the JWT; the domain trusts the adapter's
    /// pre-validation).
    #[must_use]
    pub fn slash_confirmed(&self) -> bool {
        self.slash_command || self.signed_config_flag.is_some()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slash_confirmed_when_slash_command_true() {
        let c = OperatorConfirmation {
            slash_command: true,
            oob_ack: false,
            signed_config_flag: None,
        };
        assert!(c.slash_confirmed());
    }

    #[test]
    fn slash_confirmed_when_signed_config_flag_present() {
        let c = OperatorConfirmation {
            slash_command: false,
            oob_ack: false,
            signed_config_flag: Some(SignedConfigFlag {
                jwt: "header.payload.sig".into(),
                key_id: "k1".into(),
            }),
        };
        assert!(c.slash_confirmed());
    }

    #[test]
    fn slash_not_confirmed_when_both_absent() {
        let c = OperatorConfirmation {
            slash_command: false,
            oob_ack: false,
            signed_config_flag: None,
        };
        assert!(!c.slash_confirmed());
    }
}
