//! `OobChallenge` — Out-of-Band confirmation challenge value object.

use merkle_types::{ChallengeId, Handle, NamespaceId, OobChannel, Rfc3339Timestamp, Sensitivity};
use serde::{Deserialize, Serialize};

use crate::oob::ecies_envelope::EciesEnvelope;

/// An Out-of-Band confirmation challenge issued when a `sensitivity=high`
/// Reveal is initiated.
///
/// Per [ADR-0011 Amendment], every challenge carries a 32-byte `request_nonce`
/// generated by `OsRng`.  The nonce is request-scoped and must not be reused
/// across challenges.
///
/// Per [ADR-0019], the Vault Agent MAY encrypt the inner payload (including
/// `secret_handle`) for the enrolled Companion Device using ECIES.  When the
/// `envelope` field is `Some`, all subscribers other than the enrolled device
/// receive opaque ciphertext.  The routing fields (`challenge_id`, `oob_channel`,
/// `expires_at`) remain in plaintext in the outer event envelope.
///
/// [ADR-0011 Amendment]: ../../../docs/arch/adr/0011-slash-only-reveal-with-oob-for-high-sensitivity.md
/// [ADR-0019]: ../../../docs/arch/adr/0019-ecies-encryption-for-oob-challenge-payload.md
///
/// ```
/// use merkle_types::{ChallengeId, Handle, NamespaceId, OobChannel, Sensitivity};
/// use merkle_types::Rfc3339Timestamp;
/// use merkle_domain_access_mediation::oob::challenge::OobChallenge;
///
/// let _challenge = OobChallenge {
///     challenge_id: "018f4c1a-0000-7000-8000-000000000000".parse::<ChallengeId>().unwrap(),
///     namespace_id: "018f4c1a-0000-7000-8000-000000000001".parse::<NamespaceId>().unwrap(),
///     secret_handle: "vault://prod/ssh-key/bastion".parse::<Handle>().unwrap(),
///     sensitivity: Sensitivity::High,
///     oob_channel: OobChannel::DesktopNotif,
///     expires_at: Rfc3339Timestamp::now(),
///     request_nonce: [0u8; 32],
///     envelope: None,
/// };
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OobChallenge {
    /// UUIDv7 uniquely identifying this challenge.
    pub challenge_id: ChallengeId,
    /// The namespace the secret belongs to.
    pub namespace_id: NamespaceId,
    /// The secret handle being revealed.  When `envelope` is `Some`, this
    /// field is also present inside the ECIES ciphertext (encrypted copy).
    pub secret_handle: Handle,
    /// Sensitivity of the secret.
    pub sensitivity: Sensitivity,
    /// The OOB channel through which the confirmation request is delivered.
    pub oob_channel: OobChannel,
    /// RFC 3339 timestamp after which this challenge is invalid.
    pub expires_at: Rfc3339Timestamp,
    /// 32-byte random nonce generated by `OsRng` at challenge creation time.
    /// Bound into the Ed25519 signature produced by the Companion Device to
    /// prevent replay attacks.
    pub request_nonce: [u8; 32],
    /// Optional ECIES-encrypted inner payload (ADR-0019).  Present when the
    /// enrolled Companion Device has an X25519 public key in the Sealed State.
    pub envelope: Option<EciesEnvelope>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use merkle_types::{
        ChallengeId, Handle, NamespaceId, OobChannel, Rfc3339Timestamp, Sensitivity,
    };

    fn make_challenge() -> OobChallenge {
        OobChallenge {
            challenge_id: "018f4c1a-0000-7000-8000-000000000000"
                .parse::<ChallengeId>()
                .expect("parse challenge_id"),
            namespace_id: "018f4c1a-0000-7000-8000-000000000001"
                .parse::<NamespaceId>()
                .expect("parse namespace_id"),
            secret_handle: "vault://prod/ssh-key/bastion"
                .parse::<Handle>()
                .expect("parse handle"),
            sensitivity: Sensitivity::High,
            oob_channel: OobChannel::DesktopNotif,
            expires_at: Rfc3339Timestamp::now(),
            request_nonce: [0xAB; 32],
            envelope: None,
        }
    }

    #[test]
    fn serde_json_round_trip_no_envelope() {
        let ch = make_challenge();
        let json = serde_json::to_string(&ch).expect("serialize");
        let back: OobChallenge = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(ch.challenge_id, back.challenge_id);
        assert_eq!(ch.request_nonce, back.request_nonce);
        assert!(back.envelope.is_none());
    }

    #[test]
    fn serde_json_round_trip_with_envelope() {
        use crate::oob::ecies_envelope::EciesEnvelope;
        let mut ch = make_challenge();
        ch.envelope = Some(EciesEnvelope {
            ephemeral_pubkey: [0x01; 32],
            nonce: [0x02; 24],
            ciphertext: vec![0x03, 0x04],
            aead_tag: [0x05; 16],
        });
        let json = serde_json::to_string(&ch).expect("serialize");
        let back: OobChallenge = serde_json::from_str(&json).expect("deserialize");
        assert!(back.envelope.is_some());
    }
}
